### ISSUE TITLE
Google Fonts QA report

### ISSUE THREAD

**Issue by m4rc1e** [bluemix/vibes-typeface#1]
## Fontbakery report

Fontbakery version: 0.7.9

<details>
<summary><b>[5] Vibes-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2019 AbdElmomen Kadhim (blueMix) (https://github.com/bluemix/vibes-typeface)'
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2019 AbdElmomen Kadhim (blueMix) (https://github.com/bluemix/vibes-typeface)'

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
* ⚠ **WARN** OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni2215	Contours detected: 2	Expected: 1
Glyph name: quoteleft	Contours detected: 0	Expected: 1
Glyph name: quoteright	Contours detected: 0	Expected: 1
Glyph name: quotedblleft	Contours detected: 0	Expected: 2
Glyph name: quotedblright	Contours detected: 0	Expected: 2
Glyph name: quotedblbase	Contours detected: 1	Expected: 2
Glyph name: bullet	Contours detected: 3	Expected: 1
Glyph name: guilsinglleft	Contours detected: 0	Expected: 1
Glyph name: guilsinglright	Contours detected: 0	Expected: 1
Glyph name: uni1E9E	Contours detected: 2	Expected: 1
Glyph name: guillemotleft	Contours detected: 0	Expected: 2
Glyph name: guillemotright	Contours detected: 0	Expected: 2
Glyph name: germandbls	Contours detected: 2	Expected: 1
Glyph name: fraction	Contours detected: 0	Expected: 1
Glyph name: lozenge	Contours detected: 0	Expected: 2

</details>
<details>
<summary>⚠ <b>WARN:</b> Does GPOS table have kerning information?</summary>

* [com.google.fonts/check/gpos_kerning_info](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gpos.html#com.google.fonts/check/gpos_kerning_info)
* ⚠ **WARN** GPOS table lacks kerning information.

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 1 | 4 | 72 | 7 | 75 |
| 0% | 1% | 3% | 45% | 4% | 47% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

## Diff images: [vibes_qa.zip](http://35.188.158.120/media/26cf3816-f36a-4ab0-8296-7d227ff111f4/vibes_qa.zip)

**Comment by m4rc1e** [comment]
Could you also write a short description which describes the typeface? Here is an example from https://fonts.google.com/specimen/Hepta+Slab

> Hepta Slab is a slab-serif revival based on specimens of antique genre types from Bruce and Co., primarily Antique 307. The family is a variable font which consists of 10 weights with the extremes intended for display use and the middle weights for setting text.

> To contribute, see github.com/mjlagattuta/Hepta-Slab.

**Comment by bluemix** [comment]
I've updated the description. it hope it is suffice.

**Comment by bluemix** [comment]
bty, ```FAIL: Copyright notices match canonical pattern in fonts```
i couldn't get overcome this failure check, i tried a lot, but reached the same result.
i hope, if you can give me solution on how to pass this check.
thanks in advance.

**Comment by m4rc1e** [comment]
The copyright should be:

> Copyright 2019 The Vibes Project Authors (https://github.com/bluemix/vibes-typeface)

Update it and I'll push the fonts.

**Comment by bluemix** [comment]
ok, the copyright is now updated.

**Comment by m4rc1e** [comment]
All good thanks. PR made to google/fonts https://github.com/google/fonts/pull/2141
